name: docker image set ci

on:
  push:
    branches: [ main ]

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  cloudflare_ddns:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  cockpit_machines:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  firefox:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  jellyfin:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  pi_dashboard:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  shell:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  ssserver:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
  xunlei:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-to: type=inline
