name: docker image set ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: 【login】
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: 【setup】qemu
        uses: docker/setup-qemu-action@v1
      -
        name: 【setup】docker
        uses: docker/setup-buildx-action@v1
      -
        name: 【build】caddy
        uses: docker/build-push-action@v2
        with:
          push: true
          context: caddy
          file: caddy/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:latest
