name: docker image set ci

on:
  push:
    branches: [ main ]

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  cloudflare_ddns:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  cockpit_machines:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  firefox:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  jellyfin:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
      -
        name: Build Docker Intel QVS
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile.intel
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:intel
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache_intel
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache_intel,mode=max
      -
        name: Build Docker Intel QVS on LinuxServer
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile.linuxserver
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:intel_linux
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache_intel_linux
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache_intel_linux,mode=max
  pi_dashboard:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  shell:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  ssserver:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  xunlei:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  pi_openwrt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  frp:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  zerotier:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  linux_dash:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
  qbittorrent:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
