---
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/frpc_ingress.yml
      - frpc_ingress/**
jobs:
  frpc_ingress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.job }}
          file: ${{ github.job }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}:buildcache,mode=max
      - name: Push Docker Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.job }}
          short-description: '使用参考 README，信息参考：https://www.dosk.win/'
